---
title: "Developing Data Products Notes"
author: "Coursera Course by John Hopkins University"
date: "INSTRUCTORS: Dr. Brian Caffo, Dr. Jeff Leek, Dr. Roger D. Peng"
fontsize: 11pt
output: 
  pdf_document:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro  


## Github Link for Lectures  
**[Developing Data Products' lectures on GitHub](https://github.com/DataScienceSpecialization/Developing_Data_Products)**  

## Course Book  
**[The book for this course is available on leanpub](https://leanpub.com/ddp)** 

## Instructor's Note  
"*This course is about building tools for improving the data analysis process, making data driven decisions, or for other infrastructure that supports other data products...*  
*To preview some of the topics we'll be covering. With the R Markdown package you can create websites, PDFs, presentations, and even e-books from a single file in R in a way that you're very comfortable and familiar with. We'll teach the latest features of the Shiny package which you can use to create interactive web applications in R. We'll talk about interactive graphics using Plotly and Leaflet which allows you to create beautiful maps that you can share online. We'll do similar things with the package GoogleViz which allows you to create maps and interactive graphics and tables. We've also added how to use swirl and swirlify to design courses in R so that you can share your knowledge...*  
  
*- Brian Caffo and the Data Science Track Team*"


**Reminder to Commit (Intro), Delete this line** ***AFTER*** **Committing**  

# Shiny, GoogleVis, and Plotly  
## Shiny Part 1  

### Shiny Overview 

### Shinyapps.io Project  


### Shiny (1.1)  


### Shiny (1.2)


### Shiny (1.3)  


### Shiny (1.4)  


### Shiny (1.5)  


**Reminder to Commit (01), Delete this line** ***AFTER*** **Committing**  

## Shiny Part 2  

### Shiny (2.1)  


### Shiny (2.2)  


### Shiny (2.3)  


### Shiny (2.4)  


### Shiny (2.5)  


### Shiny (2.6)  


**Reminder to Commit (02), Delete this line** ***AFTER*** **Committing**  

## Shiny Gadgets  

### Shiny Gadgets (1.1)  


### Shiny Gadgets (1.2)  


### Shiny Gadgets (1.3)  


**Reminder to Commit (03), Delete this line** ***AFTER*** **Committing**  

## GoogleVis  
### GoogleVis (1.1)  


### GoogleVis(1.2)  


**Reminder to Commit (04), Delete this line** ***AFTER*** **Committing**  

## Plotly  
### Plotly (1.1)  


### Plotly (1.2)  


### Plotly (1.3)  


### Plotly (1.4)  


### Plotly (1.5)  


### Plotly (1.6)  


### Plotly (1.7)  


### Plotly (1.8)  


**Reminder to Commit (05), Delete this line** ***AFTER*** **Committing**  

## Quiz 1  
1. 


2. 


3. 


4. 


5. 


**Reminder to Commit (Q1), Delete this line** ***AFTER*** **Committing**  


# R Markdown and Leaflet  
## R Markdown  


### R Markdown (1.1)  


### R Markdown (1.2)  


### R Markdown (1.3)  


### R Markdown (1.4)  


### R Markdown (1.5)  


### R Markdown (1.6)  


### Sharing R Markdown Documents  


**Reminder to Commit (06), Delete this line** ***AFTER*** **Committing**  

## Leaflet  


### Leaflet (1.1)  


### Leaflet (1.2)  


### Leaflet (1.3)  


### Leaflet (1.4)  


### Leaflet (1.5)  


### Leaflet (1.6)  


**Reminder to Commit (07), Delete this line** ***AFTER*** **Committing**  

## Quiz 2  
1. 


2. 


3. 


4. 


5. 


6. 


**Reminder to Commit (Q2), Delete this line** ***AFTER*** **Committing**  


## Course Project 1  



**Reminder to Commit (P1), Delete this line** ***AFTER*** **Committing**  

# Building R Packages  

## R Packages  

### R Packages Overview  


### R Packages (1.1)  


### R Packages (1.2)  


### Building R Packages Demo  



**Reminder to Commit (08), Delete this line** ***AFTER*** **Committing**  

## R Classes and Methods  
### R Classes and Methods (1.1)  


### R Classes and Methods (1.2)  


**Reminder to Commit (09), Delete this line** ***AFTER*** **Committing**  

## Quiz 3  
1. 


2. 


3. 


4. 



**Reminder to Commit (Q3), Delete this line** ***AFTER*** **Committing**  


## Course Project 2  


**Reminder to Commit (P2), Delete this line** ***AFTER*** **Committing**  


# Swirl  
## Swirl  
### Swirl (1.1)  


### Swirl (1.2)  


### Swirl (1.3)  



**Reminder to Commit (10), Delete this line** ***AFTER*** **Committing**  

## Course Project 3  


**Reminder to Commit (P3), Delete this line** ***BEFORE*** **Committing**  




